
title: JuYeop Blog
email: yeop7382@kookmin.ac.kr
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leejuyeop.github.io" # the base hostname & protocol for your site, e.g. http://example.com


sass:
  sass_dir: _sass

# Build settings
remote_theme: samarsault/texture
theme: texture
plugins:
  - jekyll-feed


texture:
  title: Lee's fantastic blog
  tagline: Student, Developer
  date_format: "%b %-d, %Y"
  style: [black]
  showNav : false
  showPicker : false

  social_links:
    twitter: thelehhman
    github:  LeeJuYeop
    linkedIn: in/thelehhman # format: locale/username
    rss : rss

comment:
  provider:       "disqus"
  disqus:
    shortname:    "leejuyeop"